2023-07-25 18:06:16.557 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-25 18:06:16.557 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration snooz which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-25 18:06:16.558 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration dreo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-25 18:06:17.101 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2023-07-25 18:06:17.125 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=30 from 2023-07-25 23:47:22.423947)
2023-07-25 18:06:19.670 ERROR (MainThread) [custom_components.hacs] HACS is disabled - invalid_token
2023-07-25 18:06:19.673 ERROR (MainThread) [custom_components.hacs] Bad credentials
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 464, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/base.py", line 522, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Bad credentials
2023-07-25 18:28:25.079 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2023-07-25 18:31:22.516 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0x4f'
2023-07-25 18:31:57.984 WARNING (MainThread) [pyatv.support.http] Got response without having a request: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'Date': 'Wed, 26 Jul 2023 01:31:57 GMT', 'Content-Length': '0', 'Server': 'AirTunes/695.5.1', 'CSeq': '11'}, body='')
2023-07-25 18:35:09.683 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 131, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-07-25 18:35:10.770 ERROR (MainThread) [custom_components.hacs] <Integration JeffSteinbok/hass-dreo> HttpStatusCode.UNAUTHORIZED
2023-07-25 18:35:10.781 ERROR (MainThread) [custom_components.hacs] <Integration hacs/integration> HttpStatusCode.UNAUTHORIZED
2023-07-25 18:35:10.859 ERROR (MainThread) [custom_components.hacs] <Integration hacs/integration> HttpStatusCode.UNAUTHORIZED
2023-07-25 18:35:10.863 ERROR (MainThread) [custom_components.hacs] <Integration JeffSteinbok/hass-dreo> HttpStatusCode.UNAUTHORIZED
2023-07-25 18:35:10.898 ERROR (MainThread) [custom_components.hacs] HACS is disabled - invalid_token
2023-07-25 18:35:10.920 ERROR (MainThread) [custom_components.hacs] <QueueManager> No manifest.json file found 'custom_components/None/manifest.json'
2023-07-25 18:35:10.922 ERROR (MainThread) [custom_components.hacs] <QueueManager> No manifest.json file found 'custom_components/None/manifest.json'
2023-07-25 18:35:10.998 ERROR (MainThread) [custom_components.hacs] <QueueManager> No manifest.json file found 'custom_components/None/manifest.json'
2023-07-25 18:35:10.999 ERROR (MainThread) [custom_components.hacs] <QueueManager> No manifest.json file found 'custom_components/None/manifest.json'
